<a href="https://colab.research.google.com/github/FGC97/project2_Henry_DataAnalytics/blob/main/ETL_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import pandas as pd
import numpy as np

import requests

import warnings
warnings.filterwarnings('ignore')

Consumir datos de la API:

* https://datosabiertos.enacom.gob.ar/dashboards/20000/acceso-a-internet/

In [ ]:
# Authentication Key
auth_key = 'GQjU3EEFwSSgRbtL3ZTOUB2MsTwf1AGDUmarZpyT'

The provided code snippet serves as a demonstration of the data extraction process from the API. It includes an attempt to extract datasets using the given GUIDs. However, due to encountered errors during the extraction process, not all the necessary datasets were successfully downloaded.

Although some datasets were not retrieved, alternative datasets were used instead to ensure the continuity of the analysis. These alternative datasets contain similar information and are deemed suitable replacements for the missing ones.

The code is included in the notebook to showcase the data extraction workflow and to illustrate the initial intent of retrieving the necessary datasets. It highlights the challenges faced during the extraction process and demonstrates the adaptability in finding alternative solutions to ensure the availability of data for further analysis.

Como hacerlo para CSV

In [ ]:
import requests

guids = ['PENET-DE-INTER-FIJO-57760', 'PENET-POR-HOGAR-NACIO-DEL', 'TOTAL-NACIO-DE-ACCES-48866',
         'BANDA-ANCHA-Y-BANDA-ANGOS', 'SERIE-TRIME-DE-ACCES-A', 'ACCES-A-INTER-FIJO-POR', 'VELOC-PROME-DE-BAJAD-DE',
         'DISTR-DE-LOS-ACCES-76145', 'ACCES-A-INTER-FIJO-23248', 'ACCES-A-INTER-FIJO-97624', 'INGRE-TRIME-POR-LA-PREST',
         'ACCES-A-INTER-FIJO-16249', 'ACCES-A-INTER-FIJO-62463', 'LISTA-DE-LOCAL-CON-CONEC', 'CONEC-AL-SERVI-DE-INTER']

# List of GUID names

for guid in guids:
    url = f'https://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/{guid}/data.csv/?auth_key={auth_key}'

    # Send GET request to the API with the URL for each GUID
    response = requests.get(url)

    if response.status_code == 200:
        # If the response status code is 200 (success), proceed with saving the file
        result = response.content

        # Create the file path and name based on the GUID
        file_name = f'/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/{guid}.csv'

        # Open the file in binary write mode and write the content
        with open(file_name, 'wb') as file:
            file.write(result)

        # Print a success message
        print(f'File "{file_name}" saved successfully.')
    else:
        # If there is an error in the request, print the error message
        print(f'Error in the request for GUID "{guid}":', response.status_code)

Error in the request for GUID "PENET-DE-INTER-FIJO-57760": 500
Error in the request for GUID "PENET-POR-HOGAR-NACIO-DEL": 500
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/TOTAL-NACIO-DE-ACCES-48866.csv" saved successfully.
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/BANDA-ANCHA-Y-BANDA-ANGOS.csv" saved successfully.
Error in the request for GUID "SERIE-TRIME-DE-ACCES-A": 500
Error in the request for GUID "ACCES-A-INTER-FIJO-POR": 500
Error in the request for GUID "VELOC-PROME-DE-BAJAD-DE": 500
Error in the request for GUID "DISTR-DE-LOS-ACCES-76145": 500
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/ACCES-A-INTER-FIJO-23248.csv" saved successfully.
Error in the request for GUID "ACCES-A-INTER-FIJO-97624": 500
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/INGRE-TRIME-POR-LA-PREST.csv" saved successfully.
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/ACCES-A-INTER-FIJO-16249.csv" saved successfully.
Error in the request for GUID "ACCES-A-INTER-FIJO-62463": 500
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/LISTA-DE-LOCAL-CON-CONEC.csv" saved successfully.
File "/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data API/Internet Data/CONEC-AL-SERVI-DE-INTER.csv" saved successfully.

Due to the unavailability of all datasets from the API, we have chosen to select Henry's datasets, which can be found in the following link. Please note that these datasets only contain data up to the first quarter of 2022.

# **ETL**

# **Internet Datasets**

In [ ]:
# Importo los csv relacionados por provincia, año y trimestre
internet_rangos_vel_prov = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Acceso_Internet_Fijo_por_rangos_velocidad_bajada_y_provincia.csv', sep = ',', dtype = str)
acceso_int_fijo_tecn_provincia = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Acceso_Internet_fijo_por_tecnología_y_provincia.csv', sep = ',', dtype = str)
acceso_banda_provincia = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Accesos_banda_ancha_y_angosta_por_provincia.csv', sep = ',', dtype = str)
penetracion_inter_fijo_100_hogares = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Penetración_de _Internet fijo _(accesos _cada_100 hogares).csv', sep = ',', dtype = str)
velocidad_media_bajada_provincia =  pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Velocidad_media_bajada_Internet_fijo_por_provincia.csv', sep = ',', dtype = str)

## **DF Acceso_Internet_Fijo_por_rangos_velocidad_bajada_y_provincia**

In [ ]:
print(internet_rangos_vel_prov.info())
(internet_rangos_vel_prov.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  792 non-null    object
 1   Trimestre            792 non-null    object
 2   Provincia            792 non-null    object
 3   HASTA 512 kbps       792 non-null    object
 4   + 512 Kbps - 1 Mbps  792 non-null    object
 5   + 1 Mbps - 6 Mbps    792 non-null    object
 6   + 6 Mbps - 10 Mbps   792 non-null    object
 7   + 10 Mbps - 20 Mbps  792 non-null    object
 8   + 20 Mbps - 30 Mbps  792 non-null    object
 9   + 30 Mbps            792 non-null    object
 10  OTROS                786 non-null    object
 11  Total                792 non-null    object
dtypes: object(12)
memory usage: 74.4+ KB
None

,Año,Trimestre,Provincia,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,OTROS,Total
0,2022,1,Buenos Aires,31.591,30.056,313.382,321.756,290.127,161.183,3.381.049,26.280,4.555.424
1,2022,1,Capital Federal,527,5.575,39.918,77.390,61.053,43.289,1.188.072,1.717,1.417.541
2,2022,1,Catamarca,71,456,4.386,7.009,8.773,3.761,35.715,2.207,62.378

### *Analisis del DataFrame 'acceso_int_fijo_rangos_vel_bajada_provincia'*
* En primer lugar se puede notar que hay 6 datos nulos en la columa 'OTROS', se debe revisar a que corresponden. De igual manera, esta columna no la usare para hacer un merge, entonces las reviso depués.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Los datos numericos estan con '.' como separador decimal, entonces debo reemplazar esos '.' por '' y después convertirlos en float para poder trabajar con ellos, no puedo ponerlos en int porque hay nulos.
* Hago una lista para acordarme de las columnas
* ['HASTA 512 kbps','+ 512 Kbps - 1 Mbps','+ 1 Mbps - 6 Mbps','+ 6 Mbps - 10 Mbps','+ 10 Mbps - 20 Mbps','+ 20 Mbps - 30 Mbps','+ 30 Mbps', 'OTROS ' , 'Total ' ]
* También cambiare los tipos de datos de las columnas 'Trimestre' y 'Año' a tipo **int**

In [ ]:
numeric_data = ['HASTA 512 kbps', '+ 512 Kbps - 1 Mbps', '+ 1 Mbps - 6 Mbps',
                '+ 6 Mbps - 10 Mbps', '+ 10 Mbps - 20 Mbps', '+ 20 Mbps - 30 Mbps',
                '+ 30 Mbps', 'OTROS', 'Total']

for column in numeric_data:
    # Remove dots in the column values
    internet_rangos_vel_prov[column] = internet_rangos_vel_prov[column].str.replace('.', '')

# Convert columns to float type
internet_rangos_vel_prov[numeric_data] = internet_rangos_vel_prov[numeric_data].astype(float)

<ipython-input-333-60d904bdb69e>:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  internet_rangos_vel_prov[column] = internet_rangos_vel_prov[column].str.replace('.', '')

In [ ]:
# Convert colums to int type
internet_rangos_vel_prov[['Trimestre','Año']] = internet_rangos_vel_prov[['Trimestre','Año']] .astype(int)

In [ ]:
internet_rangos_vel_prov['Año'].value_counts()
# Todo normal

2021    96
2020    96
2019    96
2018    96
2017    96
2016    96
2015    96
2014    96
2022    24
Name: Año, dtype: int64

In [ ]:
# Verify the changes
print(internet_rangos_vel_prov.info())
internet_rangos_vel_prov.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  792 non-null    int64
 1   Trimestre            792 non-null    int64
 2   Provincia            792 non-null    object
 3   HASTA 512 kbps       792 non-null    float64
 4   + 512 Kbps - 1 Mbps  792 non-null    float64
 5   + 1 Mbps - 6 Mbps    792 non-null    float64
 6   + 6 Mbps - 10 Mbps   792 non-null    float64
 7   + 10 Mbps - 20 Mbps  792 non-null    float64
 8   + 20 Mbps - 30 Mbps  792 non-null    float64
 9   + 30 Mbps            792 non-null    float64
 10  OTROS                786 non-null    float64
 11  Total                792 non-null    float64
dtypes: float64(9), int64(2), object(1)
memory usage: 74.4+ KB
None

,Año,Trimestre,Provincia,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,OTROS,Total
0,2022,1,Buenos Aires,31591.0,30056.0,313382.0,321756.0,290127.0,161183.0,3381049.0,26280.0,4555424.0
1,2022,1,Capital Federal,527.0,5575.0,39918.0,77390.0,61053.0,43289.0,1188072.0,1717.0,1417541.0
2,2022,1,Catamarca,71.0,456.0,4386.0,7009.0,8773.0,3761.0,35715.0,2207.0,62378.0

## **Datasets**: (Merge ['Año','Trimestre' 'Provincia'])


* Acceso_Internet_fijo_por_tecnología_y_provincia

* Accesos_banda_ancha_y_angosta_por_provincia

* Penetración_de _Internet fijo _(accesos _cada_100 hogares)

* Velocidad_media_bajada_Internet_fijo_por_provincia

## **DF Acceso_Internet_fijo_por_tecnología_y_provincia**

In [ ]:
print(acceso_int_fijo_tecn_provincia.info())
acceso_int_fijo_tecn_provincia.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           793 non-null    object
 1   Trimestre     793 non-null    object
 2   Provincia     792 non-null    object
 3   ADSL          792 non-null    object
 4   Cablemodem    792 non-null    object
 5   Fibra óptica  792 non-null    object
 6   Wireless      792 non-null    object
 7   Otros         792 non-null    object
 8   Total         792 non-null    object
dtypes: object(9)
memory usage: 55.9+ KB
None

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,1,Buenos Aires,392.045,2.728.865,1.242.121,125.521,66.872,4.555.424
1,2022,1,Capital Federal,102.290,1.217.225,62.308,5.784,29.934,1.417.541
2,2022,1,Catamarca,14.181,15.517,29.118,1.328,2.234,62.378

### *Analisis del DataFrame 'Acceso_Internet_fijo_por_tecnología_y_provincia'*
* Puedo notar que hay 1 dato nulo en las columas numericas se deben revisar a que corresponden. De igual manera, estas columnas no las usare para hacer un merge, entonces las reviso depués.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Los datos numericos estan con '.' como separador decimal, entonces debo reemplazar esos '.' por '' y después convertirlos en float para poder trabajar con ellos, no puedo ponerlos en int porque hay nulos.
* Hago una lista para acordarme de las columnas
* ['ADSL','Cablemodem', 'Fibra óptica', 'Wireless ', 'Otros', 'Total']

In [ ]:
numeric_data = ['ADSL','Cablemodem', 'Fibra óptica', 'Wireless', 'Otros', 'Total']

for column in numeric_data:
    # There was some values with '- 0', so I replaced them by '0'
    acceso_int_fijo_tecn_provincia[column] = acceso_int_fijo_tecn_provincia[column].str.replace('- 0', '0')
    # Remove dots in the column values
    acceso_int_fijo_tecn_provincia[column] = acceso_int_fijo_tecn_provincia[column].str.replace('.', '')

# Convert columns to float type
acceso_int_fijo_tecn_provincia[numeric_data] = acceso_int_fijo_tecn_provincia[numeric_data].astype(float)

<ipython-input-338-d8952f8fa89f>:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  acceso_int_fijo_tecn_provincia[column] = acceso_int_fijo_tecn_provincia[column].str.replace('.', '')

### **Error**
* Se descubrio que en  las columnas 'Trimestre' y 'Año' hay algunos valores con un * en ellos (Ejemplo: 3 *, 2019 *).
* Tambien hay una fila que en la columna 'Año' tiene el valor de *, y en la columna 'Trimestre' el valor de 'Los datos provinciales no coinciden a nivel nacional, ya que se rincorporó información que no contien apertuta a nivel geográfico.'
* No sabiendo con claridad que significa el mensaje, como el enfoque y los datos de este analisis corresponden a nivel de provincia y no a nivel nacional, procedo a eliminar esos errores para poder hacer un merge exitoso. Los datos de total coinciden con los del dataframe 'Accesos_banda_ancha_y_angosta_por_provincia'.

In [ ]:
print(acceso_int_fijo_tecn_provincia['Año'].value_counts())
print(acceso_int_fijo_tecn_provincia['Trimestre'].value_counts())

2021      96
2020      96
2018      96
2017      96
2016      96
2015      96
2014      96
2019 *    72
2022      24
2019      24
*          1
Name: Año, dtype: int64
1                                                                                                                                     192
4                                                                                                                                     192
3                                                                                                                                     168
2                                                                                                                                     168
3 *                                                                                                                                    24
2 *                                                                                                                                    24
1 *                                                                                                                                    24
Los datos provinciales no coinciden a nivel nacional, ya que se rincorporó información que no contien apertuta a nivel geográfico.      1
Name: Trimestre, dtype: int64

In [ ]:

# Look for the value that in 'Año' = * and in 'Trimestre' = 'Los datos provinciales no coinciden a nivel nacional, ya que se rincorporó información que no contien apertuta a nivel geográfico.'
# index 792
acceso_int_fijo_tecn_provincia[acceso_int_fijo_tecn_provincia['Trimestre'] == 'Los datos provinciales no coinciden a nivel nacional, ya que se rincorporó información que no contien apertuta a nivel geográfico.']

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
792,*,Los datos provinciales no coinciden a nivel na...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
acceso_int_fijo_tecn_provincia[acceso_int_fijo_tecn_provincia['Año'] == '2019 *']
# Error

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
240,2019 *,3 *,Buenos Aires,1277249.0,2144956.0,425386.0,85572.0,27070.0,3960233.0
241,2019 *,3 *,Capital Federal,300288.0,1080973.0,24900.0,3895.0,31155.0,1441211.0
242,2019 *,3 *,Catamarca,24349.0,5543.0,13.0,244.0,2251.0,32400.0
243,2019 *,3 *,Chaco,50416.0,49156.0,8063.0,5224.0,1592.0,114451.0
244,2019 *,3 *,Chubut,37298.0,27090.0,1917.0,15149.0,7551.0,89005.0
...,...,...,...,...,...,...,...,...,...
307,2019 *,1 *,Santa Cruz,10659.0,4615.0,382.0,6514.0,2735.0,24905.0
308,2019 *,1 *,Santa Fe,340038.0,340344.0,15621.0,23215.0,17860.0,737078.0
309,2019 *,1 *,Santiago Del Estero,25337.0,61547.0,23.0,2847.0,99.0,89853.0
310,2019 *,1 *,Tierra Del Fuego,19789.0,23549.0,1623.0,0.0,1486.0,46447.0
311,2019 *,1 *,Tucumán,159215.0,11670.0,118.0,678.0,321.0,172002.0

In [ ]:
# Reemplazo los asteriscos '*' por "":
acceso_int_fijo_tecn_provincia['Trimestre'] = acceso_int_fijo_tecn_provincia['Trimestre'].apply(lambda x: x.replace(' *', ''))
acceso_int_fijo_tecn_provincia['Año'] = acceso_int_fijo_tecn_provincia['Año'].apply(lambda x: x.replace(' *', ''))

In [ ]:
# Verify the changes
print(acceso_int_fijo_tecn_provincia.info())
acceso_int_fijo_tecn_provincia.head(3)

# The Null values that appear in those columns correspond directly to the same error. I will use inner joint later so the issue will be fixed.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Año           793 non-null    object
 1   Trimestre     793 non-null    object
 2   Provincia     792 non-null    object
 3   ADSL          792 non-null    float64
 4   Cablemodem    792 non-null    float64
 5   Fibra óptica  792 non-null    float64
 6   Wireless      792 non-null    float64
 7   Otros         792 non-null    float64
 8   Total         792 non-null    float64
dtypes: float64(6), object(3)
memory usage: 55.9+ KB
None

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,1,Buenos Aires,392045.0,2728865.0,1242121.0,125521.0,66872.0,4555424.0
1,2022,1,Capital Federal,102290.0,1217225.0,62308.0,5784.0,29934.0,1417541.0
2,2022,1,Catamarca,14181.0,15517.0,29118.0,1328.0,2234.0,62378.0

## **DF Accesos_banda_ancha_y_angosta_por_provincia**

In [ ]:
print(acceso_banda_provincia.info())
acceso_banda_provincia.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Año               792 non-null    object
 1   Trimestre         792 non-null    object
 2   Provincia         792 non-null    object
 3   Banda ancha fija  792 non-null    object
 4   Dial up           790 non-null    object
 5   Total             792 non-null    object
dtypes: object(6)
memory usage: 37.2+ KB
None

    Año Trimestre        Provincia Banda ancha fija Dial up      Total
0  2022         1     Buenos Aires        4.549.131   6.293  4.555.424
1  2022         1  Capital Federal        1.415.378   2.163  1.417.541
2  2022         1        Catamarca           62.377       1     62.378

### *Analisis del DataFrame 'Accesos_banda_ancha_y_angosta_por_provincia'*
* Puedo notar que hay 2 datos nulos en la columa 'Dial up' se debe revisar a que corresponden. De igual manera, esta columna no la usare para hacer un merge, entonces las reviso depués.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Los datos numericos estan con '.' como separador decimal, entonces debo reemplazar esos '.' por '' y después convertirlos en float para poder trabajar con ellos, no puedo ponerlos en int porque hay nulos.
Hago una lista para acordarme de las columnas
* ['Banda ancha fija','Dial up','Total']

In [ ]:
numeric_data = ['Banda ancha fija','Dial up','Total']

for column in numeric_data:
    # There was some values with '- 0', so I replaced them by '0'
    acceso_banda_provincia[column] = acceso_banda_provincia[column].str.replace('- 0', '0')
    # Remove dots in the column values
    acceso_banda_provincia[column] = acceso_banda_provincia[column].str.replace('.', '')

# Convert columns to float type
acceso_banda_provincia[numeric_data] = acceso_banda_provincia[numeric_data].astype(float)

<ipython-input-345-36af544cc6d8>:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  acceso_banda_provincia[column] = acceso_banda_provincia[column].str.replace('.', '')

In [ ]:
print(acceso_banda_provincia.info())
acceso_banda_provincia.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Año               792 non-null    object
 1   Trimestre         792 non-null    object
 2   Provincia         792 non-null    object
 3   Banda ancha fija  792 non-null    float64
 4   Dial up           790 non-null    float64
 5   Total             792 non-null    float64
dtypes: float64(3), object(3)
memory usage: 37.2+ KB
None

    Año Trimestre        Provincia  Banda ancha fija  Dial up      Total
0  2022         1     Buenos Aires         4549131.0   6293.0  4555424.0
1  2022         1  Capital Federal         1415378.0   2163.0  1417541.0
2  2022         1        Catamarca           62377.0      1.0    62378.0

## **DF Penetración_de _Internet fijo _(accesos _cada_100 hogares)**

In [ ]:
print(penetracion_inter_fijo_100_hogares.info())
penetracion_inter_fijo_100_hogares.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           792 non-null    object
 1   Trimestre                     792 non-null    object
 2   Provincia                     792 non-null    object
 3   Accesos por cada 100 hogares  792 non-null    object
dtypes: object(4)
memory usage: 24.9+ KB
None

    Año Trimestre        Provincia Accesos por cada 100 hogares
0  2022         1     Buenos Aires                        76,08
1  2022         1  Capital Federal                        111,8
2  2022         1        Catamarca                        58,21

### *Analisis del DataFrame 'Penetración_de _Internet fijo _(accesos _cada_100 hogares)'*
* Puedo notar que no hay datos nulos.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Los datos numericos estan con ',' como separador decimal, entonces debo reemplazar esos ',' por '' y después convertirlos en float para poder trabajar con ellos, no puedo ponerlos en int porque hay nulos.
Hago una lista para acordarme de las columnas
* ['Accesos por cada 100 hogares']

In [ ]:
numeric_data = ['Accesos por cada 100 hogares']


for column in numeric_data:
    # Remove coma in the column values
    penetracion_inter_fijo_100_hogares[column] = penetracion_inter_fijo_100_hogares[column].str.replace(',', '')

# Convert columns to float type
penetracion_inter_fijo_100_hogares[numeric_data] = penetracion_inter_fijo_100_hogares[numeric_data].astype(float)

In [ ]:
print(penetracion_inter_fijo_100_hogares.info())
penetracion_inter_fijo_100_hogares.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           792 non-null    object
 1   Trimestre                     792 non-null    object
 2   Provincia                     792 non-null    object
 3   Accesos por cada 100 hogares  792 non-null    float64
dtypes: float64(1), object(3)
memory usage: 24.9+ KB
None

    Año Trimestre        Provincia  Accesos por cada 100 hogares
0  2022         1     Buenos Aires                        7608.0
1  2022         1  Capital Federal                        1118.0
2  2022         1        Catamarca                        5821.0

## **DF Velocidad_media_bajada_Internet_fijo_por_provincia**

In [ ]:
print(velocidad_media_bajada_provincia.info())
velocidad_media_bajada_provincia.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     792 non-null    object
 1   Trimestre               792 non-null    object
 2   Provincia               792 non-null    object
 3   Mbps (Media de bajada)  792 non-null    object
dtypes: object(4)
memory usage: 24.9+ KB
None

    Año Trimestre        Provincia Mbps (Media de bajada)
0  2022         1     Buenos Aires                     63
1  2022         1  Capital Federal                     88
2  2022         1        Catamarca                     51

### *Analisis del DataFrame 'Velocidad_media_bajada_Internet_fijo_por_provincia'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Debo cambiar el tipo de dato de la columna ['Mbps (Media de bajada)'] a float

In [ ]:
# Convert columns to float type
velocidad_media_bajada_provincia['Mbps (Media de bajada)'] = velocidad_media_bajada_provincia['Mbps (Media de bajada)'].astype(float)

## **Inner Merge (['Año','Trimestre' 'Provincia'])**

* Acceso_Internet_fijo_por_tecnología_y_provincia

* Accesos_banda_ancha_y_angosta_por_provincia

* Penetración_de _Internet fijo _(accesos _cada_100 hogares)

* Velocidad_media_bajada_Internet_fijo_por_provincia

In [ ]:
# Hago merge de las 4 datasets, eliminando la columna repetida 'Total' de uno de ellos.
internet_prov = acceso_int_fijo_tecn_provincia.merge(acceso_banda_provincia.drop('Total', axis = 1), on=['Año', 'Trimestre', 'Provincia']).merge(penetracion_inter_fijo_100_hogares, on=['Año', 'Trimestre', 'Provincia']).merge(velocidad_media_bajada_provincia, on=['Año', 'Trimestre', 'Provincia'])

In [ ]:
internet_prov.head()

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Banda ancha fija,Dial up,Accesos por cada 100 hogares,Mbps (Media de bajada)
0,2022,1,Buenos Aires,392045.0,2728865.0,1242121.0,125521.0,66872.0,4555424.0,4549131.0,6293.0,7608.0,63.0
1,2022,1,Capital Federal,102290.0,1217225.0,62308.0,5784.0,29934.0,1417541.0,1415378.0,2163.0,1118.0,88.0
2,2022,1,Catamarca,14181.0,15517.0,29118.0,1328.0,2234.0,62378.0,62377.0,1.0,5821.0,51.0
3,2022,1,Chaco,32391.0,64546.0,36662.0,8164.0,2356.0,144119.0,144114.0,5.0,4406.0,46.0
4,2022,1,Chubut,44133.0,66667.0,9184.0,30592.0,21052.0,171628.0,170701.0,927.0,8805.0,13.0

In [ ]:
# Verifico valores nulos
print(internet_prov.isnull().sum())

# Verifico valores duplicados
print(internet_prov.duplicated().sum())

Año                             0
Trimestre                       0
Provincia                       0
ADSL                            0
Cablemodem                      0
Fibra óptica                    0
Wireless                        0
Otros                           0
Total                           0
Banda ancha fija                0
Dial up                         2
Accesos por cada 100 hogares    0
Mbps (Media de bajada)          0
dtype: int64
0

In [ ]:
# Nos damos cuenta que los valores nulos de la columna 'Dial up' corresponden a un valor de 0, debido a que la sumatoria da ese resultado, entonces imputamos esos datos con 0.
print(internet_prov[internet_prov['Dial up'].isnull()])

# Imputo el valor en nulos igual a 0
internet_prov['Dial up'].fillna(0, inplace=True)

# Compruebo
internet_prov.isnull().sum()

      Año Trimestre Provincia     ADSL  Cablemodem  Fibra óptica  Wireless  \
368  2018         2   Formosa  23543.0      7311.0          18.0   13625.0
373  2018         2  Misiones  57265.0     47923.0         512.0     391.0

     Otros     Total  Banda ancha fija  Dial up  Accesos por cada 100 hogares  \
368   57.0   44554.0           44554.0      NaN                        2943.0
373   56.0  106147.0          106147.0      NaN                        3163.0

     Mbps (Media de bajada)
368                     9.0
373                    12.0

Año                             0
Trimestre                       0
Provincia                       0
ADSL                            0
Cablemodem                      0
Fibra óptica                    0
Wireless                        0
Otros                           0
Total                           0
Banda ancha fija                0
Dial up                         0
Accesos por cada 100 hogares    0
Mbps (Media de bajada)          0
dtype: int64

* También cambiare los tipos de datos de las columnas 'Trimestre' y 'Año' a tipo **int**

In [ ]:
# Convert colums to int type
internet_prov[['Trimestre','Año']] = internet_prov[['Trimestre','Año']] .astype(int)

## **Datasets**: (Merge ['Provincia','Partido' 'Localidad'])

* Accesos_Internet_fijo_por_tecnología_y_localidad
* Conectividad_al_servicio_Internet

In [ ]:
# Importo los csv relacionados por provincia, partido y localidad
acceso_int_fijo_tecn_localidad = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Accesos_Internet_fijo_por_tecnología_y_localidad.csv', sep = ',', dtype = str)
conectividad_internet = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Conectividad_al_servicio_Internet.csv', sep = ',', dtype = str)

## **DF Accesos_Internet_fijo_por_tecnología_y_localidad**

In [ ]:
print(acceso_int_fijo_tecn_localidad.info())
acceso_int_fijo_tecn_localidad.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3127 entries, 0 to 3126
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      3127 non-null   object
 1   Partido        3127 non-null   object
 2   Localidad      3127 non-null   object
 3   Link Indec     3127 non-null   object
 4   ADSL           3127 non-null   object
 5   CABLEMODEM     3127 non-null   object
 6   DIAL UP        3127 non-null   object
 7   FIBRA OPTICA   3127 non-null   object
 8   OTROS          3127 non-null   object
 9   SATELITAL      3127 non-null   object
 10  WIMAX          3127 non-null   object
 11  WIRELESS       3127 non-null   object
 12  Total general  3127 non-null   object
 13  Unnamed: 13    0 non-null      object
dtypes: object(14)
memory usage: 342.1+ KB
None

,Provincia,Partido,Localidad,Link Indec,ADSL,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,WIMAX,WIRELESS,Total general,Unnamed: 13
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,914,4.704,- 0,5,- 0,975,- 0,664,7.262,NaN
1,BUENOS AIRES,25 de Mayo,Del Valle,6854020,181,- 0,- 0,- 0,10,1,- 0,- 0,192,NaN
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,- 0,- 0,- 0,- 0,- 0,- 0,- 0,181,181,NaN

### *Analisis del DataFrame 'Accesos_Internet_fijo_por_tecnología_y_localidad'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Los nombres de provincia estan en mayusculas, **los pondré normal en el merge**.
* Hay algunos valores en las columnas numericas que tienen valores con '-0', hay que reemplazarlos por 0.
* Debo cambiar el tipo de dato de la columna ['ADSL','CABLEMODEM','DIAL UP','FIBRA OPTICA', 'OTROS','SATELITAL','WIMAX', 'WIRELESS' , 'Total general'] a float.
* Hay una columna 'Unnamed:13' vacia, hay que eliminarla.
* Hay una columna 'Link Indec' que no tiene relación con nuestro analisis, entonces la eliminare.

In [ ]:
numeric_data= ['ADSL','CABLEMODEM','DIAL UP','FIBRA OPTICA',
           'OTROS','SATELITAL','WIMAX', 'WIRELESS' , 'Total general' ]

# Remove coma in the column values
acceso_int_fijo_tecn_localidad[numeric_data] = acceso_int_fijo_tecn_localidad[numeric_data].apply(lambda x: x.str.replace('.', ''))

# There was some values with '- 0', so I replaced them by '0'
acceso_int_fijo_tecn_localidad[numeric_data] = acceso_int_fijo_tecn_localidad[numeric_data].apply(lambda x: x.str.replace('- 0', '0'))

# Convert columns to float type
acceso_int_fijo_tecn_localidad[numeric_data] = acceso_int_fijo_tecn_localidad[numeric_data].astype(float)

<ipython-input-359-b7846d0f0b1c>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  acceso_int_fijo_tecn_localidad[numeric_data] = acceso_int_fijo_tecn_localidad[numeric_data].apply(lambda x: x.str.replace('.', ''))

In [ ]:
# Drop the empty column
acceso_int_fijo_tecn_localidad.drop('Unnamed: 13', axis = 1, inplace=True)

# Drop the 'Link Indec' colum, we won´t need it
acceso_int_fijo_tecn_localidad.drop('Link Indec', axis = 1, inplace=True)

In [ ]:
print(acceso_int_fijo_tecn_localidad.info())
acceso_int_fijo_tecn_localidad.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3127 entries, 0 to 3126
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      3127 non-null   object
 1   Partido        3127 non-null   object
 2   Localidad      3127 non-null   object
 3   ADSL           3127 non-null   float64
 4   CABLEMODEM     3127 non-null   float64
 5   DIAL UP        3127 non-null   float64
 6   FIBRA OPTICA   3127 non-null   float64
 7   OTROS          3127 non-null   float64
 8   SATELITAL      3127 non-null   float64
 9   WIMAX          3127 non-null   float64
 10  WIRELESS       3127 non-null   float64
 11  Total general  3127 non-null   float64
dtypes: float64(9), object(3)
memory usage: 293.3+ KB
None

,Provincia,Partido,Localidad,ADSL,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,WIMAX,WIRELESS,Total general
0,BUENOS AIRES,25 de Mayo,25 de Mayo,914.0,4704.0,0.0,5.0,0.0,975.0,0.0,664.0,7262.0
1,BUENOS AIRES,25 de Mayo,Del Valle,181.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,192.0
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,0.0,0.0,0.0,0.0,0.0,0.0,0.0,181.0,181.0

## **DF Conectividad_al_servicio_Internet**

In [ ]:
print(conectividad_internet.info())
conectividad_internet.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4312 entries, 0 to 4311
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      4312 non-null   object
 1   Partido        4312 non-null   object
 2   Localidad      4312 non-null   object
 3   Poblacion      4312 non-null   object
 4   ADSL           4312 non-null   object
 5   CABLEMODEM     4312 non-null   object
 6   DIALUP         4312 non-null   object
 7   FIBRAOPTICA    4312 non-null   object
 8   SATELITAL      4312 non-null   object
 9   WIRELESS       4312 non-null   object
 10  TELEFONIAFIJA  4312 non-null   object
 11  3G             4312 non-null   object
 12  4G             4312 non-null   object
 13  link           3836 non-null   object
 14  Latitud        4312 non-null   object
 15  Longitud       4312 non-null   object
dtypes: object(16)
memory usage: 539.1+ KB
None

,Provincia,Partido,Localidad,Poblacion,ADSL,CABLEMODEM,DIALUP,FIBRAOPTICA,SATELITAL,WIRELESS,TELEFONIAFIJA,3G,4G,link,Latitud,Longitud
0,BUENOS AIRES,25 de Mayo,25 de Mayo,23408,SI,SI,--,SI,SI,SI,SI,SI,SI,6854100,-35.4339385892588,-60.1731209454056
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,280,--,--,--,--,--,--,SI,--,--,6854010,-35.7392169542026,-60.5590634621789
2,BUENOS AIRES,25 de Mayo,Del Valle,899,SI,--,--,--,SI,--,--,SI,SI,6854020,-35.8973453887603,-60.7316089512944

### *Analisis del DataFrame 'Conectividad_al_servicio_Internet'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Debo cambiar el tipo de dato de la columna ['Poblacion','Latitud','Longitud'] a float
* Eliminar la columna 'link' ya que no la usaré

In [ ]:
numeric_data= ['Poblacion','Latitud','Longitud']

# Convert columns to float type
conectividad_internet[numeric_data] = conectividad_internet[numeric_data].astype(float)

In [ ]:
conectividad_internet.drop('link', inplace = True, axis = 1)

In [ ]:
print(conectividad_internet.info())
conectividad_internet.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4312 entries, 0 to 4311
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      4312 non-null   object
 1   Partido        4312 non-null   object
 2   Localidad      4312 non-null   object
 3   Poblacion      4312 non-null   float64
 4   ADSL           4312 non-null   object
 5   CABLEMODEM     4312 non-null   object
 6   DIALUP         4312 non-null   object
 7   FIBRAOPTICA    4312 non-null   object
 8   SATELITAL      4312 non-null   object
 9   WIRELESS       4312 non-null   object
 10  TELEFONIAFIJA  4312 non-null   object
 11  3G             4312 non-null   object
 12  4G             4312 non-null   object
 13  Latitud        4312 non-null   float64
 14  Longitud       4312 non-null   float64
dtypes: float64(3), object(12)
memory usage: 505.4+ KB
None

,Provincia,Partido,Localidad,Poblacion,ADSL,CABLEMODEM,DIALUP,FIBRAOPTICA,SATELITAL,WIRELESS,TELEFONIAFIJA,3G,4G,Latitud,Longitud
0,BUENOS AIRES,25 de Mayo,25 de Mayo,23408.0,SI,SI,--,SI,SI,SI,SI,SI,SI,-35.433939,-60.173121
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,280.0,--,--,--,--,--,--,SI,--,--,-35.739217,-60.559063
2,BUENOS AIRES,25 de Mayo,Del Valle,899.0,SI,--,--,--,SI,--,--,SI,SI,-35.897345,-60.731609

## **Inner Merge (['Provincia','Partido' 'Localidad'])**

* Accesos_Internet_fijo_por_tecnología_y_localidad
* Conectividad_al_servicio_Internet

In [ ]:
internet_loc = acceso_int_fijo_tecn_localidad.merge(conectividad_internet.drop(['ADSL', 'CABLEMODEM', 'DIALUP', 'FIBRAOPTICA', 'SATELITAL', 'WIRELESS'], axis=1), on=['Provincia', 'Partido', 'Localidad'])

In [ ]:
# Cambio el orden de las columnas
column_order = ['Provincia', 'Partido', 'Localidad', 'Poblacion', 'ADSL', 'CABLEMODEM', 'FIBRA OPTICA', 'SATELITAL', 'WIMAX', 'WIRELESS', 'DIAL UP', 'OTROS', 'Total general', 'TELEFONIAFIJA', '3G', '4G', 'Latitud', 'Longitud']
internet_loc = internet_loc[column_order]

Revisare nulos y duplicados

In [ ]:
# Verify null values
print(internet_loc.isnull().sum())

# Verify duplicated values
internet_loc.duplicated().sum()

Provincia        0
Partido          0
Localidad        0
Poblacion        0
ADSL             0
CABLEMODEM       0
FIBRA OPTICA     0
SATELITAL        0
WIMAX            0
WIRELESS         0
DIAL UP          0
OTROS            0
Total general    0
TELEFONIAFIJA    0
3G               0
4G               0
Latitud          0
Longitud         0
dtype: int64

2

Hay 2 valores duplicados, procedo a identificarlos y eliminarlos.

In [ ]:
# Select rows with duplicated values in the DataFrame
internet_loc[internet_loc.duplicated(keep=False)]
# keep=False ensures that all duplicate rows are selected and included in the final result, while non-duplicate rows are excluded.

,Provincia,Partido,Localidad,Poblacion,ADSL,CABLEMODEM,FIBRA OPTICA,SATELITAL,WIMAX,WIRELESS,DIAL UP,OTROS,Total general,TELEFONIAFIJA,3G,4G,Latitud,Longitud
1383,ENTRE RIOS,Paraná,El Ramblón,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,18.0,--,--,SI,-31.848047,-60.092749
1384,ENTRE RIOS,Paraná,El Ramblón,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,18.0,--,--,SI,-31.848047,-60.092749
2068,RIO NEGRO,General Roca,Barrio La Costa,94.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,--,--,--,-39.075307,-67.539226
2069,RIO NEGRO,General Roca,Barrio La Costa,94.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,--,--,--,-39.075307,-67.539226

In [ ]:
# Drop duplicated values
internet_loc.drop_duplicates(inplace = True)

# Verify duplicated values
internet_loc.duplicated().sum()

0

In [ ]:
internet_loc.info()
internet_loc.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2966 entries, 0 to 2967
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      2966 non-null   object
 1   Partido        2966 non-null   object
 2   Localidad      2966 non-null   object
 3   Poblacion      2966 non-null   float64
 4   ADSL           2966 non-null   float64
 5   CABLEMODEM     2966 non-null   float64
 6   FIBRA OPTICA   2966 non-null   float64
 7   SATELITAL      2966 non-null   float64
 8   WIMAX          2966 non-null   float64
 9   WIRELESS       2966 non-null   float64
 10  DIAL UP        2966 non-null   float64
 11  OTROS          2966 non-null   float64
 12  Total general  2966 non-null   float64
 13  TELEFONIAFIJA  2966 non-null   object
 14  3G             2966 non-null   object
 15  4G             2966 non-null   object
 16  Latitud        2966 non-null   float64
 17  Longitud       2966 non-null   float64
dtypes: float64(12), object(6)
memory usage: 440.3+ KB

,Provincia,Partido,Localidad,Poblacion,ADSL,CABLEMODEM,FIBRA OPTICA,SATELITAL,WIMAX,WIRELESS,DIAL UP,OTROS,Total general,TELEFONIAFIJA,3G,4G,Latitud,Longitud
0,BUENOS AIRES,25 de Mayo,25 de Mayo,23408.0,914.0,4704.0,5.0,975.0,0.0,664.0,0.0,0.0,7262.0,SI,SI,SI,-35.433939,-60.173121
1,BUENOS AIRES,25 de Mayo,Del Valle,899.0,181.0,0.0,0.0,1.0,0.0,0.0,0.0,10.0,192.0,--,SI,SI,-35.897345,-60.731609
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,547.0,0.0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,181.0,--,--,--,-35.164397,-60.081358
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,4524.0,0.0,782.0,0.0,0.0,0.0,327.0,0.0,18.0,1127.0,SI,SI,SI,-35.272779,-59.771933
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,63.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0,--,--,--,-35.483827,-59.988065

## **DF Ingresos_trimestrales_prestación_servicio_Internet_fijo**

In [ ]:
# Importo los csv relacionados por provincia, año y trimestre
internet_income = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Internet/Ingresos_trimestrales_prestación_servicio_Internet_fijo.csv', sep = ',', dtype = str)

In [ ]:
print(internet_income.info())
internet_income.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Año                        33 non-null     object
 1   Trimestre                  33 non-null     object
 2   Ingresos (miles de pesos)  33 non-null     object
 3   Periodo                    33 non-null     object
dtypes: object(4)
memory usage: 1.2+ KB
None

    Año Trimestre Ingresos (miles de pesos)        Periodo
0  2022         1                51.432.896   Ene-Mar 2022
1  2021         4                45.467.887   Oct-Dic 2021
2  2021         3                42.999.944  Jul-Sept 2021
3  2021         2                38.239.667   Abr-Jun 2021
4  2021         1                36.676.371   Ene-Mar 2021

### *Analisis del DataFrame 'Ingresos_trimestrales_prestación_servicio_Internet_fijo'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Debo cambiar el tipo de dato de la columna ['Ingresos (miles de pesos)'] a float
* También cambiare los tipos de datos de las columnas 'Trimestre' y 'Año' a tipo **int**
* Eliminar la columna 'Periodo' ya que tenemos la información del Trimestre y del Año, entonces es redundante.

In [ ]:
numeric_data= ['Ingresos (miles de pesos)']

# Remove coma in the column values
internet_income[numeric_data] = internet_income[numeric_data].apply(lambda x: x.str.replace('.', ''))

# Convert columns to float type
internet_income[numeric_data] = internet_income[numeric_data].astype(float)

<ipython-input-374-d8696138a9af>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  internet_income[numeric_data] = internet_income[numeric_data].apply(lambda x: x.str.replace('.', ''))

In [ ]:
# Convert columns to int type
internet_income[['Trimestre', 'Año']] = internet_income[['Trimestre', 'Año']].astype(int)

In [ ]:
# Drop 'Periodo' column
internet_income.drop('Periodo', axis = 1, inplace = True)

In [ ]:
print(internet_income.info())
internet_income.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Año                        33 non-null     int64
 1   Trimestre                  33 non-null     int64
 2   Ingresos (miles de pesos)  33 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 920.0 bytes
None

    Año  Trimestre  Ingresos (miles de pesos)
0  2022          1                 51432896.0
1  2021          4                 45467887.0
2  2021          3                 42999944.0
3  2021          2                 38239667.0
4  2021          1                 36676371.0

In [ ]:
print(internet_rangos_vel_prov.info())
internet_rangos_vel_prov.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  792 non-null    int64
 1   Trimestre            792 non-null    int64
 2   Provincia            792 non-null    object
 3   HASTA 512 kbps       792 non-null    float64
 4   + 512 Kbps - 1 Mbps  792 non-null    float64
 5   + 1 Mbps - 6 Mbps    792 non-null    float64
 6   + 6 Mbps - 10 Mbps   792 non-null    float64
 7   + 10 Mbps - 20 Mbps  792 non-null    float64
 8   + 20 Mbps - 30 Mbps  792 non-null    float64
 9   + 30 Mbps            792 non-null    float64
 10  OTROS                786 non-null    float64
 11  Total                792 non-null    float64
dtypes: float64(9), int64(2), object(1)
memory usage: 74.4+ KB
None

,Año,Trimestre,Provincia,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,OTROS,Total
0,2022,1,Buenos Aires,31591.0,30056.0,313382.0,321756.0,290127.0,161183.0,3381049.0,26280.0,4555424.0
1,2022,1,Capital Federal,527.0,5575.0,39918.0,77390.0,61053.0,43289.0,1188072.0,1717.0,1417541.0
2,2022,1,Catamarca,71.0,456.0,4386.0,7009.0,8773.0,3761.0,35715.0,2207.0,62378.0
3,2022,1,Chaco,461.0,1099.0,16888.0,21235.0,20898.0,13012.0,62946.0,7580.0,144119.0
4,2022,1,Chubut,113.0,1677.0,61369.0,31856.0,33080.0,13871.0,14055.0,15607.0,171628.0

In [ ]:
print(internet_loc.info())
internet_loc.head(5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2966 entries, 0 to 2967
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      2966 non-null   object
 1   Partido        2966 non-null   object
 2   Localidad      2966 non-null   object
 3   Poblacion      2966 non-null   float64
 4   ADSL           2966 non-null   float64
 5   CABLEMODEM     2966 non-null   float64
 6   FIBRA OPTICA   2966 non-null   float64
 7   SATELITAL      2966 non-null   float64
 8   WIMAX          2966 non-null   float64
 9   WIRELESS       2966 non-null   float64
 10  DIAL UP        2966 non-null   float64
 11  OTROS          2966 non-null   float64
 12  Total general  2966 non-null   float64
 13  TELEFONIAFIJA  2966 non-null   object
 14  3G             2966 non-null   object
 15  4G             2966 non-null   object
 16  Latitud        2966 non-null   float64
 17  Longitud       2966 non-null   float64
dtypes: float64(12), object(6)
memory usage: 440.3+ KB
None

,Provincia,Partido,Localidad,Poblacion,ADSL,CABLEMODEM,FIBRA OPTICA,SATELITAL,WIMAX,WIRELESS,DIAL UP,OTROS,Total general,TELEFONIAFIJA,3G,4G,Latitud,Longitud
0,BUENOS AIRES,25 de Mayo,25 de Mayo,23408.0,914.0,4704.0,5.0,975.0,0.0,664.0,0.0,0.0,7262.0,SI,SI,SI,-35.433939,-60.173121
1,BUENOS AIRES,25 de Mayo,Del Valle,899.0,181.0,0.0,0.0,1.0,0.0,0.0,0.0,10.0,192.0,--,SI,SI,-35.897345,-60.731609
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,547.0,0.0,0.0,0.0,0.0,0.0,181.0,0.0,0.0,181.0,--,--,--,-35.164397,-60.081358
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,4524.0,0.0,782.0,0.0,0.0,0.0,327.0,0.0,18.0,1127.0,SI,SI,SI,-35.272779,-59.771933
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,63.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0,--,--,--,-35.483827,-59.988065

In [ ]:
print(internet_prov.info())
internet_prov.head(5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 792 entries, 0 to 791
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Año                           792 non-null    int64
 1   Trimestre                     792 non-null    int64
 2   Provincia                     792 non-null    object
 3   ADSL                          792 non-null    float64
 4   Cablemodem                    792 non-null    float64
 5   Fibra óptica                  792 non-null    float64
 6   Wireless                      792 non-null    float64
 7   Otros                         792 non-null    float64
 8   Total                         792 non-null    float64
 9   Banda ancha fija              792 non-null    float64
 10  Dial up                       792 non-null    float64
 11  Accesos por cada 100 hogares  792 non-null    float64
 12  Mbps (Media de bajada)        792 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 86.6+ KB
None

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Banda ancha fija,Dial up,Accesos por cada 100 hogares,Mbps (Media de bajada)
0,2022,1,Buenos Aires,392045.0,2728865.0,1242121.0,125521.0,66872.0,4555424.0,4549131.0,6293.0,7608.0,63.0
1,2022,1,Capital Federal,102290.0,1217225.0,62308.0,5784.0,29934.0,1417541.0,1415378.0,2163.0,1118.0,88.0
2,2022,1,Catamarca,14181.0,15517.0,29118.0,1328.0,2234.0,62378.0,62377.0,1.0,5821.0,51.0
3,2022,1,Chaco,32391.0,64546.0,36662.0,8164.0,2356.0,144119.0,144114.0,5.0,4406.0,46.0
4,2022,1,Chubut,44133.0,66667.0,9184.0,30592.0,21052.0,171628.0,170701.0,927.0,8805.0,13.0

In [ ]:
print(internet_income.info())
internet_income.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Año                        33 non-null     int64
 1   Trimestre                  33 non-null     int64
 2   Ingresos (miles de pesos)  33 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 920.0 bytes
None

    Año  Trimestre  Ingresos (miles de pesos)
0  2022          1                 51432896.0
1  2021          4                 45467887.0
2  2021          3                 42999944.0
3  2021          2                 38239667.0
4  2021          1                 36676371.0

# **Phone Datasets**

# **Fixed Phone Datasets**

In [ ]:
# Importo los csv
acc_fixed_phone_prov = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Fixed Phone/Accesos_telefonía_fija_por_provincia-hogares-comercios-gobierno-otros.csv', sep = ',', dtype = str)
quarterly_income_fixed_phone = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Fixed Phone/Ingresos_trimestrales_telefonía fija.csv', sep = ',', dtype = str)

## **DF Accesos_telefonía_fija_por_provincia-hogares-comercios-gobierno-otros**

In [ ]:
print(acc_fixed_phone_prov.info())
(acc_fixed_phone_prov.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Año                                 792 non-null    object
 1   Trimestre                           792 non-null    object
 2   Provincia                           792 non-null    object
 3   Accesos telefonía fija (total)      792 non-null    object
 4   Accesos telefonía fija (hogares)    792 non-null    object
 5   Accesos telefonía fija (comercial)  792 non-null    object
 6   Accesos telefonía fija (gobierno)   792 non-null    object
 7   Accesos telefonía fija (otros)      792 non-null    object
dtypes: object(8)
memory usage: 49.6+ KB
None

,Año,Trimestre,Provincia,Accesos telefonía fija (total),Accesos telefonía fija (hogares),Accesos telefonía fija (comercial),Accesos telefonía fija (gobierno),Accesos telefonía fija (otros)
0,2022,1,Buenos Aires,3.340.707,3.044.152,230.980,14.831,50.744
1,2022,1,Capital Federal,1.508.031,1.374.162,104.267,6.695,22.907
2,2022,1,Catamarca,30.167,27.489,2.086,134,458

### *Analisis del DataFrame 'Accesos_telefonía_fija_por_provincia-hogares-comercios-gobierno-otros'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Se deben cambiar los '.' por ''
* Debo cambiar el tipo de dato de las columnas ['Año', 'Trimestre', 'Provincia', 'Accesos telefonía fija (hogares)', 'Accesos telefonía fija (comercial)', 'Accesos telefonía fija (gobierno)', 'Accesos telefonía fija (otros)', 'Accesos telefonía fija (total)']
 a float
* También cambiare los tipos de datos de las columnas 'Trimestre' y 'Año' a tipo **int**
* Eliminar la columna 'Periodo' ya que tenemos la información del Trimestre y del Año, entonces es redundante.

In [ ]:
numeric_data = ['Accesos telefonía fija (hogares)', 'Accesos telefonía fija (comercial)', 'Accesos telefonía fija (gobierno)', 'Accesos telefonía fija (otros)', 'Accesos telefonía fija (total)']

# Remove dot in the column values
acc_fixed_phone_prov[numeric_data] = acc_fixed_phone_prov[numeric_data].apply(lambda x: x.str.replace('.', ''))

# Convert columns to float type
acc_fixed_phone_prov[numeric_data] = acc_fixed_phone_prov[numeric_data].astype(float)

<ipython-input-384-dd525caf7cbd>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  acc_fixed_phone_prov[numeric_data] = acc_fixed_phone_prov[numeric_data].apply(lambda x: x.str.replace('.', ''))

In [ ]:
numeric_data = ['Año', 'Trimestre']

# Convert columns to int type
acc_fixed_phone_prov[numeric_data] = acc_fixed_phone_prov[numeric_data].astype(int)

In [ ]:
# Cambio el orden de las columnas
column_order = ['Provincia', 'Partido', 'Localidad', 'Poblacion', 'ADSL', 'CABLEMODEM', 'FIBRA OPTICA', 'SATELITAL', 'WIMAX', 'WIRELESS', 'DIAL UP', 'OTROS', 'Total general', 'TELEFONIAFIJA', '3G', '4G', 'Latitud', 'Longitud']
internet_loc = internet_loc[column_order]

In [ ]:
# Verify null values
acc_fixed_phone_prov.isnull().sum()
# Verify duplicated values
acc_fixed_phone_prov.duplicated().sum()

0

* Me doy cuenta que las columnas ['Accesos telefonía fija (hogares)', 'Accesos telefonía fija (comercial)', 'Accesos telefonía fija (gobierno)'] no son de mucha relevancia, ya que el analisis de internet esta por provincias y totales, no discriminado por hogares, comercios y gobierno. Entonces procedo a eliminarlas

In [ ]:
acc_fixed_phone_prov.drop(['Accesos telefonía fija (hogares)', 'Accesos telefonía fija (comercial)', 'Accesos telefonía fija (gobierno)'], inplace = True, axis = 1)

In [ ]:
print(acc_fixed_phone_prov.info())
(acc_fixed_phone_prov.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Año                             792 non-null    int64
 1   Trimestre                       792 non-null    int64
 2   Provincia                       792 non-null    object
 3   Accesos telefonía fija (total)  792 non-null    float64
 4   Accesos telefonía fija (otros)  792 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 31.1+ KB
None

,Año,Trimestre,Provincia,Accesos telefonía fija (total),Accesos telefonía fija (otros)
0,2022,1,Buenos Aires,3340707.0,50744.0
1,2022,1,Capital Federal,1508031.0,22907.0
2,2022,1,Catamarca,30167.0,458.0

## **DF Ingresos_trimestrales_telefonía fija**

In [ ]:
print(quarterly_income_fixed_phone.info())
(quarterly_income_fixed_phone.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Año                    33 non-null     object
 1   Trimestre              33 non-null     object
 2   Ingresos (miles de $)  33 non-null     object
dtypes: object(3)
memory usage: 920.0+ bytes
None

    Año Trimestre Ingresos (miles de $)
0  2014         1          2.916.071,75
1  2014         2           2.974.865,2
2  2014         3          3.105.462,02

### *Analisis del DataFrame 'Ingresos_trimestrales_telefonía fija'*
* Puedo notar que no hay datos nulos
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Se deben cambiar los '.' por ''
* Se deben cambiar los ',' por '.'
* Debo cambiar el tipo de dato de las columnas 'Ingresos (miles de $)'
 a float
* También cambiare los tipos de datos de las columnas ['Año', 'Trimestre'] a tipo **int**

In [ ]:
# Remove coma in the column values
quarterly_income_fixed_phone['Ingresos (miles de $)'] = quarterly_income_fixed_phone['Ingresos (miles de $)'].apply(lambda x: x.replace('.', ''))

# Replace coma for dot in the column values
quarterly_income_fixed_phone['Ingresos (miles de $)'] = quarterly_income_fixed_phone['Ingresos (miles de $)'].apply(lambda x: x.replace(',', '.'))

# Convert columns to float type
numeric_data = ['Ingresos (miles de $)']
quarterly_income_fixed_phone[numeric_data] = quarterly_income_fixed_phone[numeric_data].astype(float)

# Convert columns to int type

numeric_data = ['Año', 'Trimestre']
quarterly_income_fixed_phone[numeric_data] = quarterly_income_fixed_phone[numeric_data].astype(int)

In [ ]:
print(quarterly_income_fixed_phone.info())
(quarterly_income_fixed_phone.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Año                    33 non-null     int64
 1   Trimestre              33 non-null     int64
 2   Ingresos (miles de $)  33 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 920.0 bytes
None

    Año  Trimestre  Ingresos (miles de $)
0  2014          1             2916071.75
1  2014          2             2974865.20
2  2014          3             3105462.02

# **Mobile Phone Datasets**

In [ ]:
# Importo los csv
quarterly_income_mobile_phone = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Mobile Phone/Ingresos_trimestrales_telefonía móvil.csv', sep = ',', dtype = str)
mothly_portability_per_operator = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Mobile Phone/Portabilidad_portaciones_netas_mensuales_por_operador.csv', sep = ',', dtype = str)
quarterly_total_acc_mobile_phone = pd.read_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Data Henry/Mobile Phone/Total_nacional_accesos_telefonia_movil-trimestral.csv', sep = ',', dtype = str)

## **DF Ingresos_trimestrales_telefonía móvil**

In [ ]:
print(quarterly_income_mobile_phone.info())
(quarterly_income_mobile_phone.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Año                    37 non-null     object
 1   Trimestre              37 non-null     object
 2   Ingresos (miles de $)  37 non-null     object
 3   Periodo                37 non-null     object
dtypes: object(4)
memory usage: 1.3+ KB
None

    Año Trimestre Ingresos (miles de $)        Periodo
0  2013         1          $ 13.135.235   Ene-Mar 2013
1  2013         2          $ 13.970.806   Abr-Jun 2013
2  2013         3          $ 15.235.659  Jul-Sept 2013

### *Analisis del DataFrame 'Ingresos_trimestrales_telefonía móvil'*

* Puedo notar que no hay datos nulos.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Se deben cambiar los '.' por ''
* Se eliminan el simbolo dolar en la columna 'Ingresos (miles de $)'

* Debo cambiar el tipo de dato de las columnas 'Ingresos (miles de $)'
 a float
* También cambiare los tipos de datos de las columnas ['Año', 'Trimestre'] a tipo **int**

In [ ]:
# Replace  "." for ""
quarterly_income_mobile_phone["Ingresos (miles de $)"] = quarterly_income_mobile_phone["Ingresos (miles de $)"].apply(lambda x: x.replace('.', ''))

# Remove $ in the column 'Ingresos (miles de $)'
quarterly_income_mobile_phone["Ingresos (miles de $)"] = quarterly_income_mobile_phone["Ingresos (miles de $)"].apply(lambda x: x.replace('$ ', ''))

# Convert columns into float type
quarterly_income_mobile_phone["Ingresos (miles de $)"] = quarterly_income_mobile_phone["Ingresos (miles de $)"].astype(float)

# Convert columns to int type
quarterly_income_mobile_phone[["Año", "Trimestre"]]= quarterly_income_mobile_phone[["Año", "Trimestre"]].astype(int)

# Remove 'Periodo' colum
quarterly_income_mobile_phone.drop("Periodo", axis=1, inplace=True)

In [ ]:
quarterly_income_mobile_phone.isnull().sum()

Año                      0
Trimestre                0
Ingresos (miles de $)    0
dtype: int64

In [ ]:
print(quarterly_income_mobile_phone.info())
quarterly_income_mobile_phone.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Año                    37 non-null     int64
 1   Trimestre              37 non-null     int64
 2   Ingresos (miles de $)  37 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 1016.0 bytes
None

    Año  Trimestre  Ingresos (miles de $)
0  2013          1             13135235.0
1  2013          2             13970806.0

## **DF Portabilidad_portaciones_netas_mensuales_por_operador.csv**

In [ ]:
print(mothly_portability_per_operator.info())
(mothly_portability_per_operator.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Año       120 non-null    object
 1   Mes       120 non-null    object
 2   Personal  120 non-null    object
 3   Claro     120 non-null    object
 4   Nextel    70 non-null     object
 5   Movistar  120 non-null    object
 6   Periodo   120 non-null    object
dtypes: object(7)
memory usage: 6.7+ KB
None

    Año Mes Personal   Claro Nextel Movistar Periodo
0  2012   3      -17      19      0       -2  Mar-12
1  2012   4    3.508  -1.134   -189   -2.185  Apr-12
2  2012   5    1.253   4.792   -853   -5.192  May-12

### *Portabilidad_portaciones_netas_mensuales_por_operador.csv*
* Puedo notar que hay 50 datos nulos en Nextel.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Se deben cambiar los '.' por '' en la columna ['Personal', 'Claro', 'Nextel', 'Movistar'] y debo cambiar el tipo de dato de las columnas  
 a float
* También cambiare los tipos de datos de las columnas ['Año', 'Mes'] a tipo **int**
* La columna 'Periodo' contiene los mismos datos de 'Año' y 'Trimestre', entonces es redundante y por eso la eliminare.

In [ ]:
numeric_columns = ['Personal', 'Claro', 'Nextel', 'Movistar']

# Replace "." in the numeric columns
mothly_portability_per_operator[numeric_columns] = mothly_portability_per_operator[numeric_columns].apply(lambda x: x.str.replace('.', ''))

# Convert columns to float type
mothly_portability_per_operator[numeric_columns] = mothly_portability_per_operator[numeric_columns].astype(float)

# Convert columns to int type
mothly_portability_per_operator[["Año", "Mes"]] = mothly_portability_per_operator[["Año", "Mes"]].astype(int)

# Remove 'Periodo' column
mothly_portability_per_operator.drop("Periodo", axis=1, inplace=True)

<ipython-input-399-9d1a47086b63>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  mothly_portability_per_operator[numeric_columns] = mothly_portability_per_operator[numeric_columns].apply(lambda x: x.str.replace('.', ''))

* I will check the number and specific values that are null in the 'Nextel' column.

* "Nextel, a telecommunications service provider, does not currently offer internet services. Nextel primarily focuses on mobile communication services such as voice calling and messaging.
* Considering this and the null values, the column related to Nextel's internet services can be removed as it is not applicable to our current Internet analisis."

In [ ]:
# Count the number of null values in the "Nextel" column
mothly_portability_per_operator['Nextel'].isnull().sum()

# Drop 'Nextel' column
mothly_portability_per_operator.drop('Nextel', inplace = True, axis = 1)

In [ ]:
print(mothly_portability_per_operator.info())
(mothly_portability_per_operator.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Año       120 non-null    int64
 1   Mes       120 non-null    int64
 2   Personal  120 non-null    float64
 3   Claro     120 non-null    float64
 4   Movistar  120 non-null    float64
dtypes: float64(3), int64(2)
memory usage: 4.8 KB
None

    Año  Mes  Personal   Claro  Movistar
0  2012    3     -17.0    19.0      -2.0
1  2012    4    3508.0 -1134.0   -2185.0
2  2012    5    1253.0  4792.0   -5192.0

## **DF Total_nacional_accesos_telefonia_movil-trimestral**

In [ ]:
print(quarterly_total_acc_mobile_phone.info())
(quarterly_total_acc_mobile_phone.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Año                          37 non-null     object
 1   Trimestre                    37 non-null     object
 2   Total de accesos pospago     37 non-null     object
 3   Total de accesos prepago     37 non-null     object
 4   Total de accesos operativos  37 non-null     object
 5   Periodo                      37 non-null     object
dtypes: object(6)
memory usage: 1.9+ KB
None

,Año,Trimestre,Total de accesos pospago,Total de accesos prepago,Total de accesos operativos,Periodo
0,2013,1,7.761.349,57.147.608,64.908.957,Ene-Mar 2013
1,2013,2,7.769.110,58.004.822,65.773.932,Abr-Jun 2013
2,2013,3,8.002.183,59.048.909,67.051.092,Jul-Sept 2013

### *Total_nacional_accesos_telefonia_movil-trimestral*
* Puedo notar que no hay valores nulos.
* Al momento de importar los dataframes, los traje como dtype = str, por lo cual debo cambiar los tipos de datos corresponientes a numericos de cada columna.
* Se deben cambiar los '.' por '' en la columna ['Total de accesos pospago', 'Total de accesos prepago', 'Total de accesos operativos', 'Movistar'] y debo cambiar el tipo de dato de las columnas
 a float
* También cambiare los tipos de datos de las columnas ['Año', 'Trimestre'] a tipo **int**
* La columna 'Periodo' contiene los mismos datos de 'Año' y 'Trimestre', entonces es redundante y por eso la eliminare.

In [ ]:
numeric_columns =  ['Total de accesos pospago', 'Total de accesos prepago', 'Total de accesos operativos']

# Replace "." in the numeric columns
quarterly_total_acc_mobile_phone[numeric_columns] = quarterly_total_acc_mobile_phone[numeric_columns].apply(lambda x: x.str.replace('.', ''))

# Convert columns to float type
quarterly_total_acc_mobile_phone[numeric_columns] = quarterly_total_acc_mobile_phone[numeric_columns].astype(float)

# Convert columns to int type
quarterly_total_acc_mobile_phone[["Año", "Trimestre"]] = quarterly_total_acc_mobile_phone[["Año", "Trimestre"]].astype(int)

# Remove 'Periodo' column
quarterly_total_acc_mobile_phone.drop("Periodo", axis=1, inplace=True)

<ipython-input-403-aff109eccea7>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  quarterly_total_acc_mobile_phone[numeric_columns] = quarterly_total_acc_mobile_phone[numeric_columns].apply(lambda x: x.str.replace('.', ''))

In [ ]:
print(quarterly_total_acc_mobile_phone.info())
(quarterly_total_acc_mobile_phone.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Año                          37 non-null     int64
 1   Trimestre                    37 non-null     int64
 2   Total de accesos pospago     37 non-null     float64
 3   Total de accesos prepago     37 non-null     float64
 4   Total de accesos operativos  37 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 1.6 KB
None

,Año,Trimestre,Total de accesos pospago,Total de accesos prepago,Total de accesos operativos
0,2013,1,7761349.0,57147608.0,64908957.0
1,2013,2,7769110.0,58004822.0,65773932.0
2,2013,3,8002183.0,59048909.0,67051092.0

# **Exportando cleaned Datasets**

##  Internet Datasets

In [ ]:
# Exportar DataFrame a un archivo CSV
internet_rangos_vel_prov.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/internet_rangos_vel_prov.csv', index=False)

# Exportar DataFrame a un archivo CSV
internet_prov.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/internet_prov.csv', index=False)

# Exportar DataFrame a un archivo CSV
internet_loc.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/internet_loc.csv', index=False)

# Exportar DataFrame a un archivo CSV
internet_income.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/internet_income.csv', index=False)

## Fixed Phone Datasets

In [ ]:
# Exportar DataFrame a un archivo CSV
acc_fixed_phone_prov.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/acc_fixed_phone_prov.csv', index=False)

# Exportar DataFrame a un archivo CSV
quarterly_income_fixed_phone.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/quarterly_income_fixed_phone.csv', index=False)

## Mobile Phone Datasets

In [ ]:
# Exportar DataFrame a un archivo CSV
quarterly_income_mobile_phone.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/quarterly_income_mobile_phone.csv', index=False)

# Exportar DataFrame a un archivo CSV
mothly_portability_per_operator.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/mothly_portability_per_operator.csv', index=False)

# Exportar DataFrame a un archivo CSV
quarterly_total_acc_mobile_phone.to_csv('/content/drive/MyDrive/Proyectos Henry/Data_Analytics_Project/Cleaned Datasets/quarterly_total_acc_mobile_phone.csv', index=False)